### ISSUE TITLE
There is no install target

### ISSUE THREAD

**Issue by dvzrv** [roc-streaming/openfec#15]
Hi! I'm currently trying to package this project, as it is a dependency of roc-toolkit.
Unfortunately that is very painful, because this project does not have an install target (although cmake is used to build it).
Having no install target is problematic especially given that a shared library is provided for which packagers would have to provide symlinks etc. themselves. That has extremely high potential for going sideways *fast*.

**Comment by gavv** [comment]
Hi, should be fixed by #14 now.

**Comment by gavv** [comment]
Let me know if we can close this.
