### ISSUE TITLE
Debian package fixes

### ISSUE THREAD

**Issue by gavv** [roc-streaming/openfec#7]
Minor issues with debian packages implemented in #5.

- [x] Rename releases from `openfec_1.2.3` to `v1.2.3` and tags from `1.2.3` to `v1.2.3`
- [x] Make packages compatible with debian: https://github.com/roc-streaming/openfec/pull/5#issuecomment-1328056622
- [x] Exclude `.c` files from `-dev` package: https://github.com/roc-streaming/openfec/pull/5#issuecomment-1328057948
- [x] Add `.pc` file to `-dev` package: https://github.com/roc-streaming/openfec/pull/5#issuecomment-1328057948
- [x] Add `lib_advanced` to include dirs in `.pc` file: https://github.com/roc-streaming/openfec/pull/5#issuecomment-1328058141
- [x] Likely, we should remove libopenfec-tools package: https://github.com/roc-streaming/openfec/pull/5#issuecomment-1328050764

**Comment by viccie30** [comment]
I can give this a go if you'd like?

**Comment by gavv** [comment]
Awesome, thanks!

**Comment by viccie30** [comment]
Looking at [Debian bug #1002724](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002724), it seems that @dankamongmen might also be interested in this.

**Comment by dankamongmen** [comment]
yeah, i had been planning on packaging this up (see https://github.com/roc-streaming/openfec/pull/4#event-7896282501), but if you already got to it, godspeed

**Comment by viccie30** [comment]
I don't use openfec and/or roc-toolkit myself (anymore), but I had packaged both some time ago. If you actually use both, I'd be happy to give the packaging code to you or co-maintain it with you, whichever you prefer.

**Comment by dankamongmen** [comment]
> I don't use openfec and/or roc-toolkit myself (anymore), but I had packaged both some time ago. If you actually use both, I'd be happy to give the packaging code to you or co-maintain it with you, whichever you prefer.

are you a DD? if so, i'm happy to comaintain, or maintain myself, or leave it to you. if not, and you'd like to become one, i'd be happy to sponsor your upload. i didn't mean to assert any claim to territory, just to let you know i've done some work here too =]. i've got packaging for it somewhere around here, but i doubt there's much difference between ours. have you pushed to salsa?

dankamongmen@gmail.com if you'd like to take this to email (either way is fine for me).

**Comment by viccie30** [comment]
I have a draft version for inclusion in Debian at https://salsa.debian.org/viccie30/openfec. Getting it uploaded to Debian depends at the very least on the resolution of #9.

**Comment by gavv** [comment]
I've edited the first sub-task in the issue:

> [...] and tags from 1.2.3 to v1.2.3

**Comment by twojstaryzdomu** [comment]
I'll try to answer those one by one:

On the  item
> Rename releases from openfec_1.2.3 to v1.2.3 and tags from 1.2.3 to v1.2.3

@gavv, have you tried editing the  variable `tag_name` and setting `release_name` with to `v${VERSION}` and `${PACKAGE}_v${VERSION}`?

**Comment by gavv** [comment]
> @gavv, have you tried editing the variable tag_name and setting release_name with to v${VERSION} and ${PACKAGE}_v${VERSION}?

Nope, I didn't try it. I guess it's what we need.

**Comment by twojstaryzdomu** [comment]
Please let me know if it worked. As for the other items, these need to be checked if they do not break a subsequent roc-toolkit build (especially the inclusion of C files), some choices may have be intentional. I will reply shortly.

**Comment by gavv** [comment]
@twojstaryzdomu Thanks, your suggestion helped!

@viccie30 I've marked `Rename releases from openfec_1.2.3 to v1.2.3 and tags from 1.2.3 to v1.2.3` as complete. See b452e08e5bb135c9fac541ce7553b7b60ceb8119

@twojstaryzdomu Regarding C files: I believe roc doesn't need them, it needs only headers.

**Comment by gavv** [comment]
Hi, I've fixed the remaining issues and tagged v1.4.2.7

**Comment by gavv** [comment]
@dankamongmen @viccie30 FYI: both openfec and roc-toolkit now build debian packages on release and attach them to release assets.

In case you would like to reuse debian/ directory from the repo, and need some adjustments, feel free to ping me.
